
[functions.generate-mission-reflection]
enabled = true
verify_jwt = true
import_map = "./functions/generate-mission-reflection/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-mission-reflection/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-mission-reflection/*.html" ]

[functions.generate-mission-statement]
enabled = true
verify_jwt = true
import_map = "./functions/generate-mission-statement/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-mission-statement/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-mission-statement/*.html" ]
